### ISSUE TITLE
LLVM's Slow-Moving AL2 Disaster Tragedy 

### ISSUE THREAD

**Issue by lbmn** [apotheon/CopyfreeWorks#29]
Is this an appropriate "forum" to discuss CI's response to LLVM re-licensing?

[See this mailing list post.](http://lists.llvm.org/pipermail/llvm-dev/2017-April/112142.html)  [[via]](http://www.phoronix.com/scan.php?page=news_item&px=LLVM-Still-Wants-Apache-2.0-L)
I'm too emotionally burned out on this issue and I'm concerned that my barging onto their mailing list would do more harm than good...

**Comment by apotheon** [comment]
I'm really not sure how to handle this at all.

I'm going to try to find time soon to set up a slightly better place for such discussion in the near future.  For now, it's fine that you brought it up here.

If anyone has any reasonable ideas for how we might be able to help dissuade the LLVM project from going down this problematic path, please share.

**Comment by apotheon** [comment]
[Did LLVM back away from the push to change its license to AL2?](https://llvm.org/docs/DeveloperPolicy.html#llvm-license)

This seems to be the most recent official word, and includes this:

> An implication of this is that the LLVM license is unlikely to ever change: changing it would require tracking down all the contributors to LLVM and getting them to agree that a license change is acceptable for their contribution. Since there are no plans to change the license, this is not a cause for concern.

I don't know whether this represents official rejection or abandonment of the license change plans, or if it's simply out-of-date info, or what.  I'd appreciate anyone who can shed some light on this doing so.

**Comment by apotheon** [comment]
Clearly, this is no longer really a question of whether it will happen.  It has happened.  I'm considering adding old versions of LLVM to the works list, but I'm not yet sure how best to do that so that it does not confuse people about the current licensing status of the LLVM project.  For now, I'm closing this issue.
